# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgtui < Formula
  desc "A simple terminal UI for PostgreSQL"
  homepage "https://github.com/pgplex/pgtui"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgplex/pgtui/releases/download/v0.3.0/pgtui_0.3.0_darwin_amd64.tar.gz"
      sha256 "affe0cdef03e241003dd35c275c99147465d7edcd410727314e7c65fb510b19a"

      def install
        bin.install "pgtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgplex/pgtui/releases/download/v0.3.0/pgtui_0.3.0_darwin_arm64.tar.gz"
      sha256 "d3039cf4a7a497268bb02f7a94af864a4a8de1ec96cd2dbb674e78bf2d4d7b95"

      def install
        bin.install "pgtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgplex/pgtui/releases/download/v0.3.0/pgtui_0.3.0_linux_amd64.tar.gz"
      sha256 "f5db95f13702dff30e6f0ea2af862463b1f3168daa022db3adf028eec910129f"
      def install
        bin.install "pgtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgplex/pgtui/releases/download/v0.3.0/pgtui_0.3.0_linux_arm64.tar.gz"
      sha256 "94cbd12b5871cb0d8163e9e8f56c57d07bc2720a049172d55935d12c40b0b88f"
      def install
        bin.install "pgtui"
      end
    end
  end

  test do
    system "#{bin}/pgtui", "--version"
  end
end
